silent! colorscheme apprentice 

set guifont=Fira\ Code:h14
set notermguicolors
set guioptions-=eT
set linespace=1
set macligatures 

" Cursor
" mode-list:argument-list,mode-list:argument-list,..
" default from docs
set guicursor=n-v-c:block-Cursor/lCursor,ve:ver35-Cursor,o:hor50-Cursor,i-ci:ver25-Cursor/lCursor,r-cr:hor20-Cursor/lCursor,sm:block-Cursor-blinkwait175-blinkoff150-blinkon175

" set guicursor=n-v-c:block-Cursor
" set guicursor+=i:ver100-iCursor
" set guicursor+=n-v-c:blinkon0
" set guicursor+=i:blinkwait10

set columns=126
set lines=48

" Quick Fonts
menu Fonts.Menlo :set guifont=Menlo:h14<CR>
menu Fonts.Monaco :set guifont=Monaco:h14<CR>
menu Fonts.Source\ Code\ Pro :set guifont=Source\ Code\ Pro:h14<CR>
menu Fonts.Office\ Code\ Pro :set guifont=Office\ Code\ Pro\ D:h14<CR>
menu Fonts.Ubuntu\ Mono :set guifont=Ubuntu\ Mono:h16<CR>
menu Fonts.Roboto\ Mono :set guifont=Roboto\ Mono:h14<CR>
menu Fonts.Roboto\ Mono\ Light :set guifont=Roboto\ Mono\ Light:h14<CR>
menu Fonts.Consolas :set guifont=Consolas:h14<CR>
menu Fonts.Inconsolata :set guifont=Inconsolata:h18<CR>
menu Fonts.Pragmata\ Pro :set guifont=Pragmata\ Pro\ Mono:h14<CR>
menu Fonts.M+\ 1mn :set guifont=M\+\ 1mn:h14<CR>
menu Fonts.Fira\ Mono :set guifont=Fira\ Mono:h14<CR>
menu Fonts.Operator\ Mono :set guifont=Operator\ Mono:h16<CR>
menu Fonts.Fira\ Code :set guifont=Fira\ Code:h14<CR>
menu Fonts.Fira\ Code\ Light :set guifont=Fira\ Code\ Light:h14<CR>
menu Fonts.Monoid :set guifont=Monoid:h14<CR>
menu Fonts.Hasklig :set guifont=Hasklig:h14<CR>
